export const COMPANY = {
    COMAPANYID: {
        WITH_FULL_KUCHIKUMUKI_OF_CATEGORY: {
            VALUE: 10013185150,
            COUNT_KUCHIKUMUKI: 212,
            COUNT_SALARY: 49,
            COUNT_WOMENT: 20,
            COUNT_KUCHIKUMUKI_OF_CATEGORY_20: 22,
            HAS_USER_LIST: true
        },
        WITHOUT_FULL_KUCHIKUMUKI_OF_CATEGORY: {
            VALUE: '00000000001',
            COUNT_KUCHIKUMUKI: 1,
            COUNT_SALARY: 1,
            COUNT_WOMENT: 0,
            HAS_USER_LIST: false
        },
        WITH_ONE_KUCHIKUMUKI_CATE_20_AND_SALARY: {
            VALUE: 10026429925,
            COUNT_SALARY: 1,
            COUNT_WOMENT: 0,
            COUNT_KUCHIKUMUKI_OF_CATEGORY_20: 1,
            HAS_USER_LIST: false
        },
        WITH_ONE_KUCHIKUMUKI_CATE_WOMEN: {
            VALUE: 10105501170,
            COUNT_KUCHIKUMUKI: 29,
            COUNT_SALARY: 15,
            COUNT_WOMENT: 1,
            COUNT_KUCHIKUMUKI_OF_CATEGORY_18: 1,
            HAS_USER_LIST: true
        }
    }
}

export const TEST_NOINDEX_COMPANY = {
    COMPANY_TOP: {
        CASE_1: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        }
    },
    COMPANY_KUCHIKOMI: {
        CASE_1: {
            COMPANYID: COMPANY.COMAPANYID.WITHOUT_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_2: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_3: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_4: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_5: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_6: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_7: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_8: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_9: {
            COMPANYID: COMPANY.COMAPANYID.WITH_ONE_KUCHIKUMUKI_CATE_20_AND_SALARY.VALUE
        },
        CASE_10: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        }
    },
    COMPANY_KYUJIN: {
        CASE_1: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        }
    },
    COMPANY_USER_LIST: {
        CASE_1: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_2: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_3: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_4: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_5: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_6: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_7: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
    },
    COMPANY_SALARY: {
        CASE_1: {
            COMPANYID: COMPANY.COMAPANYID.WITH_ONE_KUCHIKUMUKI_CATE_20_AND_SALARY.VALUE
        },
        CASE_2: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_3: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_4: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_5: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_6: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_7: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_8: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
    },
    COMPANY_WOMAN: {
        CASE_1: {
            COMPANYID: COMPANY.COMAPANYID.WITH_ONE_KUCHIKUMUKI_CATE_WOMEN.VALUE
        },
        CASE_2: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_3: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_4: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_5: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_6: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_7: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_8: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
        CASE_9: {
            COMPANYID: COMPANY.COMAPANYID.WITH_FULL_KUCHIKUMUKI_OF_CATEGORY.VALUE
        },
    },
}